### ISSUE TITLE
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect

### ISSUE THREAD

**Issue by t6productions** [tim-morriss/pyscrapeTrain#2]
Traceback (most recent call last):
  File "C:\Users\cl1ck\Desktop\AMYGDALA\pyscrapeTrain-master\scrapeTrain.py", line 164, in <module>
    scrape_train(tt_url, output_dir)
  File "C:\Users\cl1ck\Desktop\AMYGDALA\pyscrapeTrain-master\scrapeTrain.py", line 72, in scrape_train
    os.makedirs(dir_path)
  File "<frozen os>", line 225, in makedirs
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\Users\\cl1ck/pyscrapeTrain/\ndrownwithtoga\n'
PS C:\Users\cl1ck\Desktop\AMYGDALA\pyscrapeTrain-master>

**Comment by jinqiufeng** [comment]
same

**Comment by tim-morriss** [comment]
Seemed like an issue with artist names that included characters non compatible with OS. Should be fixed now.
